name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'develop'
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn --frozen-lockfile
        
      - name: Run tests
        run: yarn test
        
      - name: Codecov
        run: yarn test:cov
        
      - name: Codecov
        uses: codecov/codecov-action@v2.0.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
